config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :about, only: [:index]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
  end

  resources :users, only: [:new, :create] #allow rails to create restful routes /users/new(.:format)
  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  http_basic_authenticate_with name: ENV['ADMIN_NAME'], password: ENV['ADMIN_PASSWORD']

    # protect_from_forgery with: :exception

  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #uncomment this line to force login
  #before_filter :authorize
  
  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
  end

end
# defines what variable are available in the views file
# knows by naming convention of the views files

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_product.html.erb
<article>
  <%= link_to product_path(product) do %>
    <%= image_tag product.image.thumb.url , alt: product.name %>
    <h1>
      <span><%= product.name %></span>
      <span><%= humanized_money_with_symbol product.price %></span>
    </h1>
  <% end%>

  <% if product.quantity == 0 %>
    <button class="soldout">Sold Out </button>
    <button class ="btn disabled"> <%=fa_icon "shopping-card", text: 'Add' %> </button>

  <% else %>

  <div>
    <%= button_to add_item_cart_path(product_id: product.id), class: 'btn' ,
    method: :post do %>
      <%= fa_icon "shopping-cart", text: 'Add' %> 
    <% end %>

  <%end%>
  
  </div>
</article>

app/views/products/index.html.erb
<section class="products-index">
  <header class="page-header">
    <div class="intro">
      <p>
        Looking for a way to add some life to your home? Look no further than our online plant shop! We have a wide variety of beautiful plants and flowers, as well as all the accessories you need to keep them healthy and happy. Plus, our prices are unbeatable! So what are you waiting for?
      </p>
      <p>
        At our online plant shop, we only sell the highest quality plants and flowers. We source our products from reputable growers and nurseries, so you can be sure you're getting a healthy, beautiful plant. Plus, ordering is quick and easy! We offer free shipping on all orders over $50, so it's easy to get the plants you want without breaking the bank.
      </p>
      <p>
        We have a wide variety of plants and flowers available for purchase on our website. Whether you're looking for something small and delicate or big and bold, we have the perfect plant for you. We also carry a selection of accessories, including potting soil, pots and containers, watering cans, and more.
      </p>
    </div>
  </header>

  <div class="products">
    <%= render @products %>
  </div>
</section>

app/views/products/show.html.erb
<section class="products-show">
  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">
    <%= image_tag @product.image.url, class: 'main-img' %>
    <div>
      <h1><%= @product.name %></h1>
      <p><%= @product.description %></p>

      <div class="quantity">
        <span><%= @product.quantity %> in stock at </span>
        <span><%= humanized_money_with_symbol @product.price %></span>
      </div>

      <div class="price">      

      <% if @product.quantity == 0 %>

        <button class="soldout">Sold Out </button>
        <button class ="btn disabled"> <%=fa_icon "shopping-card", text: 'Add' %> </button>

      <% else %>

        <%= button_to add_item_cart_path(product_id: @product.id), class: 'btn' , method: :post do %>
          <%= fa_icon "shopping-cart", text: 'Add' %>
        <% end %>  

      <% end %>   

      </div>

    </div>

  </article>

</section>